services:

    _defaults:
        autowire: true
        autoconfigure: true
    
    Application\:
        resource: '../../src/Application'

    _instanceof:
        Application\Shared\Handler\HandlerInterface:
            tags: [messenger.message_handler]
