
version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dt

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
    depends_on:
      - database

  app:
    image: lalaina/ddd:latest
    ports:
      - "8000:80"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://root:admin@database:3306/dt
    volumes:
      - .:/var/www
      ###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###