
version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=booking
      - POSTGRES_PASSWORD=booking
      - POSTGRES_DB=dt

  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8080
    depends_on:
      - postgres

  booking:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: lalaina/ddd
    command: bash -c "/wait-for-it.sh postgres:5432 -s -- php bin/console d:m:m"
    restart: always
    volumes:
      - .:/var/www/
    depends_on:
      - postgres
    ports:
      - 8001:80
    environment:
      - DATABASE_URL=postgresql://booking:booking@postgres:5432/dt