
version: '3'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - .:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=devinsider
      - MYSQL_USER=devinsider
      - MYSQL_DATABASE=dt

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8001:8080
    depends_on:
      - mysql