services:

    _defaults:
        autowire: true
        autoconfigure: true
    
    Domain\:
        resource: '../../src/Domain'

    Domain\Utils\Event\EventManagerInterface: '@Infrastructure\Service\Event\EventManager'
